name: Sync Snyk

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Synchronize Snyk
        uses: snyk/actions/node@master
        with:
          command: monitor
          args: --yarn-workspaces --strict-out-of-sync=false --policy-path=.snyk --org=rugvip
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
