name: Sync Snyk

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Synchronize Snyk
        uses: snyk/actions/node@master
        with:
          command: monitor
          args: >
            --org=rugvip
            --yarn-workspaces
            --policy-path=.snyk
            --strict-out-of-sync=false
            --remote-repo-url=https://github.com/Rugvip/snyk-playground
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Create report
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        with:
          args: >
            --org=rugvip
            --yarn-workspaces
            --policy-path=.snyk
            --strict-out-of-sync=false
            --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload report
        uses: github/codeql-action/upload-sarif@v1
        with:
          category: test-cat
          sarif_file: snyk.sarif
