name: Sync Snyk

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Synchronize Snyk
        uses: snyk/actions/node@master
        with:
          command: monitor
          args: >
            --org=rugvip
            --yarn-workspaces
            --policy-path=.snyk
            --strict-out-of-sync=false
            --remote-repo-url=https://github.com/Rugvip/snyk-playground
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
