name: Vulnerability Scan

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check new dependencies for vulnerabilities.
        uses: snyk/actions/node@master
        with:
          args: >
            --org=rugvip
            --yarn-workspaces
            --policy-path=.snyk
            --strict-out-of-sync=false
            --remote-repo-url=https://github.com/Rugvip/snyk-playground
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
